language: node_js
node_js:
  - 10.13
cache:
  directories:
    - node_modules
script:
  - '[ "$TRAVIS_BRANCH" == master ] && bash ./deploy.sh'
env:
  global:
    - secure: WnBTq9Cl9PeOx1eL3yrWfHtaHAqx4GOglZ+fg4OW4qswTfWtvRik/WeaSV8S826qvkaNA6idPTsKQ5pz6kobiJZOodhILUbfez9y/JoYoXXzq4mTx8mo19DxwDFD2dWiJ63sC6qAH74xs1yF8JhgUFkAFE550DdjzvlpE0vzmTs7nEAm5WHeYFzgx3LTPOFERRsKO7TCGZD5Bl77arecWeQ/EBh9awM6ZuCdbjNUwVhtgh8VbZG16E8roIesIyujIMAIl9OIKmA1v2JLaeSVLPYrWPHiYemQjFZ397reumGUKVT8p3OsLNxoLbPAbJlenPcT7VCWnUUW0CZVtTf8bBDaufo73thCYa2JdOZL5j6c70Oe8y7GQr28GLvb29eiWkQfZSWt47V5ttJ01pfGqbFiwC8o4OqJ0vZuV+a2BpCkDrVo1CC69/92g6GTBCbIgUynpGT/IvnyzRClR2+dEqVUsdluS9IvGPQZzfq8HZIjIjpy2ELlZYpc6ykU6fReVgE0bZu5/fIpPYsFxy+dDdG9iv7dNmmwYakOgpIgFFev+m0xNB4eNBmVqzkEoN6aPk05ueSZEkjk0aKiOFzEV2hlUI49IhaR4jnSHHFrCGiHOv12i7MHSLqgSH0scI9K+U8rm/XvMxa/yd5iHQNfJv+D879HvphSKTpSkQhklLo=
