language: node_js
node_js:
- 10.13
cache:
  directories:
  - node_modules
script:
  - '[ "$TRAVIS_BRANCH" == master ] && bash ./deploy.sh'
env:
  global:
    - secure: Nk4N0JJSpJ0lsz/lIwbW3BiFALJWfZ2TCFmO1rb/04HtXyVDNraIlWuJIWsrP0wu5mQt+2XS6w460o4s7a2GaS0UY8+zHEQYom2RT4gNN6nhHmGSG84DzPPgMW1+o0NObeAnK09eDcdeaFY2+ffzoNjN/v8j4OfoG+YVqsfB7PBmGBvU82m5a2CdQh/PQs/DZU4Z0lxDiLCecosy82493y1707H1d8kFwHJAQMm1qL0rvykK3sK8L0B4CBCIa9LXvzGJ70v7Kj0lapWhIQidQok+PBlf4OafSkK/VGdqFdSqumnM3vpspe06tL1MBR6Hb+f++1nHd11wGE3/HH34wrHD7IlpyY+slJj3ziXBKPUppIE0rILVloR/hm4gOvIc3CAuEGcEll7/H8JkZKUWjP3KAQb5sCdmZPF3c80SPl8FSBNX3yhs3d3ZWVdz1paPIScPt1c97D/u+cM6lykx2psXbyjjYFunqyjNHPpYr7rxHOk+6V6gH3u0iWmWEcL+FPoLie8FzzFhITa7VgdgDVthxK/NUY/k4+zT5sVYT4BWjvp4Ei+BVCy5lOBegpIvrWtRqeKKjiLdLlyrWGXSyVtKGdKXH2vsO2GrBzFZS9K09Bk+RBaVLqfpJ9Zy8EgDE/7iv7a8eNiS+5XM07EK+tMAZsUDZ/aYOrN1+vBrMHQ=  # GH_TOKEN
    - BASE_PATH='/goodnightdream-website/'
